// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx5Rut1XlkTBDmJlzcGa-ENfLf1KaWbws',
    appId: '1:895090008251:web:e415f6a1f928ba0e49499e',
    messagingSenderId: '895090008251',
    projectId: 'travelstay247-b91d8',
    authDomain: 'travelstay247-b91d8.firebaseapp.com',
    storageBucket: 'travelstay247-b91d8.appspot.com',
    measurementId: 'G-12PQHL1B6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAITGZS3eIMOnGONE4I6RVyPjCSZnEnHs',
    appId: '1:895090008251:android:b0d061ed84aef26249499e',
    messagingSenderId: '895090008251',
    projectId: 'travelstay247-b91d8',
    storageBucket: 'travelstay247-b91d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8jnkB2-vnqQkyWQGcw-V1kvQbHnf7qJI',
    appId: '1:895090008251:ios:00588c50fd4a481849499e',
    messagingSenderId: '895090008251',
    projectId: 'travelstay247-b91d8',
    storageBucket: 'travelstay247-b91d8.appspot.com',
    iosBundleId: 'com.example.travelstay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8jnkB2-vnqQkyWQGcw-V1kvQbHnf7qJI',
    appId: '1:895090008251:ios:00588c50fd4a481849499e',
    messagingSenderId: '895090008251',
    projectId: 'travelstay247-b91d8',
    storageBucket: 'travelstay247-b91d8.appspot.com',
    iosBundleId: 'com.example.travelstay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx5Rut1XlkTBDmJlzcGa-ENfLf1KaWbws',
    appId: '1:895090008251:web:1fe98ce2d6a0843849499e',
    messagingSenderId: '895090008251',
    projectId: 'travelstay247-b91d8',
    authDomain: 'travelstay247-b91d8.firebaseapp.com',
    storageBucket: 'travelstay247-b91d8.appspot.com',
    measurementId: 'G-1SVVW1CPJV',
  );

}